language: php
php:
  - 5.4
  - 5.5
  - 5.6

before_install:
  - composer self-update

install:
  - composer install

script: "cd web && ./../vendor/bin/drush site-install --yes --db-url=sqlite://site.sqlite"
